#ifndef COMMANDHANDLERDEF_H
#define COMMANDHANDLERDEF_H

#define COMMAND_TYPE_INIT 	    1
#define COMMAND_TYPE_DEINIT 	2
#define COMMAND_TYPE_DEVINFO 	3
#define COMMAND_SET_PROP		4
#define COMMAND_TYPE_DATA 		5
#define COMMAND_TYPE_RESET		6
#define COMMAND_GET_PROP		7

#define COMMAND_STATE_DEFAULT	0
#define COMMAND_STATE_COMMAND	1
#define COMMAND_STATE_OK		2
#define COMMAND_STATE_ERROR     3

#endif
